### PR TITLE
Add telegram bot listener

### PR DESCRIPTION
**Pull request by brosahay**
Adds Telegram Client which listens to [Telegram Bot](http://under45.in/) which helps reduce unnecessary API calls to the server.

Create a free API token of telegram from [here](https://my.telegram.org/apps)

### CODE REVIEW

**Comment by vishalv26** [comment]
I don't think this is a good idea. Latency would increase.. many a times the script catches way before we get telegram message

**Comment by GirishKumarSharma** [comment]
How do I create a space for my question for this repository, I mean I have a question, where should I write and how to proceed.

**Comment by gitmnj** [comment]
Sometimes I booked with this script and after the booking gets complete. The telegram bot flashes that slots are available

**Comment by pallupz** [comment]
@GirishKumarSharma  - I have enabled Discussions tab. However, most of the discussions happens over at Discord these days. Ping me there if you're interested.

**Comment by pallupz** [comment]
@gitmnj - IIRC, telegram bots might be listening to public API which can be delayed.

**Comment by sbstratos79** [comment]
@vishalv26 I was using my own telegram channel and bot for OTP syncing and the sync times were extremely fast. I usually received the OTP before my phone rang the notification.

**Pull request closed without merging**
