### PR TITLE
Add notification support for linux and mac OS

### PR DESCRIPTION
**Pull request by SayantanRC**
Notification is useful if sound card is broken for some reason.

There might be some merge conflicts, the beep part for mac OS is implemented in `main` branch but not in this branch.
The beep part of the code is copied from `main` branch.
But I assume you are using pycharm and  such conflicts can be easily resolved.

Notification for mac OS should work fine but not tested using python. The `osascript` command seems to be working when used directly from terminal.

### CODE REVIEW

**Comment by pallupz** [comment]
dont worry about the build.. its failing due to a push.. and that doesn't work properly on pull requests

**Comment by SayantanRC** [comment]
Anyway, the code is there. You may merge this or add some modifications of your own. 😁

**Comment by SayantanRC** [comment]
Another commit added to enhance notifications on linux.
Elementary OS: https://github.com/SayantanRC/URLs/blob/master/assets/elementary.mp4
Ubuntu: https://github.com/SayantanRC/URLs/blob/master/assets/ubuntu.webm

**Comment by SayantanRC** [comment]
[Mac OS notification demo](https://drive.google.com/file/d/1yzxNMqrAzUflxExPLYQo64aon4eudvti/view?usp=drivesdk)

**Comment by SayantanRC** [comment]
Closing PR in favor of new PR: https://github.com/pallupz/covid-vaccine-booking/pull/147

**Pull request closed without merging**
