### PR TITLE
Show final details (Vaccine type, auto book, etc) before staring search.

### PR DESCRIPTION
**Pull request by SayantanRC**
This shows all final selected information.

- Vaccine type
- Auto book status (`True` or `False`)
- Start date for slot search
- Refresh interval in seconds
- Minimum slots to search for

Re-submitting as requested, in `ext-dev/info-screen`

### CODE REVIEW

**Comment by pallupz** [comment]
Thank you for this!

Between family and work, I will need some time to test this. Please do not expect a quick update to the main branch.

**Comment by SayantanRC** [comment]
No problem no problem. Take your time. Its great that we have something like this in the first place.

**Comment by pallupz** [comment]
Hi - I have implemented this but had to do it in a slight different way since the application now supports storing some info into a file. To be honest, I couldn't keep much of your code. Sorry about that.

**Comment by SayantanRC** [comment]
No no no problem. It's great that the idea got implemented. That's what matters.

**Pull request merged**
