### PR TITLE
Dockerised the packaged

### PR DESCRIPTION
**Pull request by Mitesh-82**
Added a basic docker file.

make an image using:

 docker build -t <tagname:versionname> .
 e.g. docker build -t slot-booker:version0.1 .

run the image
docker run -it <tagname:versionname>
e.g. docker run-t slot-booker:version0.1

### CODE REVIEW

**Comment by pallupz** [comment]
I dont have much experience with Docker. Do we have to create tags in the repo for this work?

**Comment by Mitesh-82** [comment]
Not required..

**Comment by pallupz** [comment]
Doesn't matter at this point. They implemented captcha.

**Comment by Mitesh-82** [comment]
Sad

**Review by Niteshkpatel — APPROVED** [review]

**Pull request closed without merging**
