### PR TITLE
Update captcha.py

### PR DESCRIPTION
**Pull request by RohanBeast**
I have changed this captcha code into grey with opencv-python.

### CODE REVIEW

**Comment by manasshukla1** [comment]
Is the whole process working for you? by changing the captcha

**Comment by manasshukla1** [comment]
Capture

Just as the slot arrives, the application shows the slot but then it throws this error "**invalid literal for int() with base 10: ''
Exiting Script**

**Comment by samdsai** [comment]
> Capture
> 
> Just as the slot arrives, the application shows the slot but then it throws this error "**invalid literal for int() with base 10: '' Exiting Script**
> 
> @pallupz Please take look into this!

This error you got after using Captcha script?

**Comment by samdsai** [comment]
> I have changed this captcha code into grey with opencv-python.

Rohan, Can you guide us how to use this script along with existing scripts ?

**Comment by manasshukla1** [comment]
> > Capture
> > Just as the slot arrives, the application shows the slot but then it throws this error "**invalid literal for int() with base 10: '' Exiting Script**
> > @pallupz Please take look into this!
> 
> This error you got after using Captcha script?

No, it was searching for slots with 5 seconds interval, and then it showed this slot. And then it never asked for choice, showed this error!

**Comment by pallupz** [comment]
@RohanBeast  - Does this really make a difference? Could you try running this & the code in main and send screenshot comparing both?

**Comment by pallupz** [comment]
Not trying to shit on you.. I couldn't see much difference is all

**Comment by RohanBeast** [comment]
Hi, this script is running in my device. I have just used opencv to turn it
to grey because it was not recognised by bots but can be with humans.

**Comment by samdsai** [comment]
Screenshot 2021-05-09 174001

Got this error while running with captcha file. any clue why it is looking for fonts ?

**Comment by pallupz** [comment]
EXE wont work

**Comment by samdsai** [comment]
sorry not understand , so you mean it will not work on EXE ?

**Comment by RohanBeast** [comment]
Hey, i have just changed the Color, font will remain same. If you are
having problems, then whatsapp me on this number.

8433447931

**Comment by RohanBeast** [comment]
And i think fonts are same, you are getting confused with color i think.
Who knows?🙄

**Comment by suaib86** [comment]
How to use this??

When i login where to click ?

Regards
Mohammad Abdul Suaib

**Comment by rheak01** [comment]
> Screenshot 2021-05-09 174001
> 
> Got this error while running with captcha file. any clue why it is looking for fonts ?

**Comment by rheak01** [comment]
> > Screenshot 2021-05-09 174001
> > Got this error while running with captcha file. any clue why it is looking for fonts ?

how to resolve this please help?

**Comment by manasshukla1** [comment]
@rheak01 Hi, the problem is with the exe file that you are using. Go to the **src** folder and open **covid-vaccine-slot-booking.py** file and book the slots from there. It will definitely work. EVEN I booked 3 slots today!

**Comment by rheak01** [comment]
@samdsai yeah there is this .txt file, named as requirements , it consists of all the module names that have to be installed before running the actual application . 
so , firstly like open command prompt and like install pip, using the command: **python -m pip install pip**, now you can install all the modules mentioned in the requirements file by passing the command:  pip install requests , pip install tabulate like  that basically pip install <module-name>. After that simply run the covid vaccination booking file from src folder and you will be able to run it .

**Comment by manasshukla1** [comment]
> > @samdsai Alternatively, as you are new to python, just go to **src** folder and then proceed with following steps:
> > 
> > 1. Press **Shift + Right Click** inside the **src** folder and click on **Open command prompt here** OR **Open Powershell window here**.
> > 2. cmd will open up. Type **python covid-vaccine-slot-booking.py**.
> > 3. Then it will ask for mobile number and then next steps are easy and you can do it yourself.
> 
> so for that we just need python 3.7version and we are good to go right?like no need to install the modules or anything?

Yupp. I never installed any modules.

**Comment by samdsai** [comment]
@manasshukla1  & @rheak01 , Great Thank you , now I have done these steps, how about captcha , 
How can I get to know , what is captcha and how to insert it ? Will it come on Power shell or Command prompt ? 
 When I got slot I selected 1.2 but later I got following error.
" Captcha Response Code : 401"  any idea what would be went wrong here ?

**Comment by rheak01** [comment]
> @manasshukla1 & @rheak01 , Great Thank you , now I have done these steps, how about captcha ,
> How can I get to know , what is captcha and how to insert it ? Will it come on Power shell or Command prompt ?
> When I got slot I selected 1.2 but later I got following error.
> " Captcha Response Code : 401" any idea what would be went wrong here ?

so basically a window will pop up on your screen and there the captcha will be there , try entering the captcha 4-5 times and your slot will be booked , press alt+tab when this captcha beep rings you will be able to see the captcha easily .

**Comment by manasshukla1** [comment]
All thanks to @**pallupz** for this wonderful project. Again thank you so much for saving our time and lives in this pandemic.

**Pull request merged**
