### PR TITLE
Enhanced captcha funtionality

### PR DESCRIPTION
**Pull request by vishalv26**

### CODE REVIEW

**Comment by pallupz** [comment]
hey man - that seems very interesting.. can you merge to ```ext-dev/captcha-gui``` branch so that I can test?

**Comment by vishalv26** [comment]
@pallupz done

**Comment by pallupz** [comment]
I am still not getting OTP.. I will update you tomorrow.. hopefully its just rate limiting

**Comment by vishalv26** [comment]
Okay.. Till the time i will try to get it tested with few people

**Pull request merged**
