### PR TITLE
Distance based sorting for nearest available center

### PR DESCRIPTION
**Pull request by mrms123**
Use input pin code / lat-long, and center pin code / lat-long to sort for the nearest available appointment

### CODE REVIEW

**Comment by pallupz** [comment]
Hey - There are a bunch of changes here and I need to test those. That could take a while.

Could you create the pull request into "feature/distance-sorting" branch? I will promote it from there after review.

**Comment by mrms123** [comment]
Sure
Will do

**Comment by mrms123** [comment]
Quick ques - is the No Viable Options messageshowing up for you now?

**Comment by pallupz** [comment]
Yea - I can see it in the latest exe. I made that into a countdown timer.
image

**Pull request merged**
